### ISSUE TITLE
Use converter HTML5s instead of builtin for Asciidoctor

### ISSUE THREAD

**Issue by jirutka** [grissius/emily-editor#80]
Please use [asciidoctor-html5s](https://github.com/jirutka/asciidoctor-html5s/) for rendering HTML output instead of builtin “html5” converter/backend – it produces much better markup. :)

I’ve made npm package for it (transpilled via Opal), but don’t run tests against it yet, so I _hope_ it works well…

**Comment by grissius** [comment]
#85
